---
- hosts: all
  become: yes

  tasks:
    - name: Installation d'Apache
      ansible.builtin.shell:
       cmd: apt install apache2 -y
    
    - name: Installation de PHP
      apt:
        pkg:
         - php
         - php-gd
         - php-mysql
         - php-curl
         - php-mbstring
         - php-intl
         - php-gmp
         - php-bcmath
         - php-imagick
         - php-xml
         - php-zip
        state: latest
        update_cache: true

    - name: Installation de Unzip
      ansible.builtin.shell:
       cmd: apt install unzip -y
    
    - name: Téléchargement de l'archive Nextcloud
      ansible.builtin.shell:
       cmd: wget /var/www/ https://download.nextcloud.com/server/releases/nextcloud-23.0.0.zip
    
    - name: Extraction de l'archive
      ansible.builtin.shell:
       cmd: unzip /var/www/nextcloud-23.0.0.zip

    - name: Attribution des droits sur le répertoire Web Nextcloud
      ansible.builtin.shell:
       cmd: chmod 755 /var/www/nextcloud

    - name: Modification du répertoire web par défaut d'Apache2 pour Nextcloud
      ansible.builtin.shell:
       cmd: sed -i 's/html/nextcloud/g' /etc/apache2/sites-available/000-default.conf

    - name: Redémarrage du service Apache2
      ansible.builtin.shell:
       cmd: systemctl restart apache2